Config = {}

Config.animDicts = {
    ["face_human@test@new_horse"] = "Hew Norse",
    ["face_human@bill_williamson@variations@aiming"] = "Bill W. Aim",
    ["face_human@gen_female_timid@variations@brave"] = "Female Brave",
    ["face_human@gen_female_agro@variations@bitchy"] = "Female Bitchy",
    ["face_human@test@mp_facial"] = "Facial",
    ["face_human@gen_female@variations@seductive"] = "Female Seductive",
    ["face_human@john_marston@variations@normal"] = "John M. Normal",
    ["face_human@gen_male_agro@variations@happy"] = "Male Happy",
    ["face_human@mini_games@blackjack@p_m_zero"] = "Blackjack",
    ["face_human@gen_female_agro@variations@defuse"] = "Female Defuse",
    ["face_human@abigail_roberts@variations@seductive"] = "Abigail Seductive",
    ["face_human@dutch@base"] = "Dutch",
    ["face_human@john_marston@base"] = "Marston",
    ["face_human@abigail_roberts@variations@normal"] = "Abigail",
    ["face_human@gen_female_timid@variations@sleeping"] = "Female Sleeping",
    ["face_human@hosea@variations@aiming"] = "Hosea",
    ["face_human@gen_female_timid@variations@defuse"] = "Female Defuse 2",
    ["face_human@gen_female@variations@exertion"] = "Female Exertion",
    ["face_human@charles_smith@variations@drunk"] = "Charles Drunk",
    ["face_human@bill_williamson@base"] = "Bill Base",
    ["face_human@mini_games@poker@gen_male"] = "Poker",
    ["face_human@test@new_head"] = "New Head",
    ["face_human@micah_bell@base"] = "Micah",
    ["face_human@gen_male@scenario@smokecig"] = "Smoke",
    ["face_human@gen_female@variations@angry"] = "Female Angry",
    ["face_human@gen_male_timid@base"] = "Male Base",
    ["face_human@gen_male@scenario@wipeface"] = "Male Wipeface",
    ["face_human@gen_male@scenario@eating"] = "Male Eat",
    ["face_human@gen_male@scenario@drinkshot"] = "Make Drink",
    ["face_human@micah_bell@variations@injured"] = "Micah Injured",
    ["face_human@abigail_roberts@variations@injured"] = "Abigail Injured",
    ["face_human@gen_male@melee@base"] = "Male Base 2",
    ["face_human@gen_male_agro@variations@drunk"] = "Male Drunk",
    ["face_human@abigail_roberts@variations@drunk"] = "Abigail Drunk",
    ["face_human@mrs_adler@base"] = "Adler Base",
    ["face_human@p_m_zero"] = "MP Base",
    ["face_human@gen_female_agro@variations@normal"] = "Female Normal",
    ["face_human@gen_female_timid@variations@angry"] = "Female Timid Angry",
    ["face_human@gen_male@variations@exertion"] = "Male Exertion",
    ["face_human@gen_female_timid@variations@curious"] = "Female Curious",
    ["face_human@gen_female@variations@aiming"] = "Female Aim",
    ["face_human@gen_male@variations@aiming"] = "Male Aim",
    ["face_human@gen_male_timid@variations@sleeping"] = "Male Sleep",
    ["face_human@gen_female@variations@curious"] = "Female Curious 2",
    ["face_human@abigail_roberts@variations@sleeping"] = "Abigail Sleep",
    ["face_human@mini_games@blackjack@gen_male"] = "Blackjack 2",
    ["face_human@gen_female@variations@happy"] = "Female Happy",
    ["face_human@micah_bell@variations@normal"] = "Micah Normal",
    ["face_human@gen_male@variations@happy"] = "Male Happy",
    ["face_human@dutch@variations@exertion"] = "Dutch Exertion",
    ["face_human@gen_male@scenario@drinkhand"] = "Male Drinkhand",
    ["FACE_HUMAN@GEN_MALE@VARIATIONS@SLEEPING"] = "Male Sleep 2",
    ["FACE_HUMAN@GEN_MALE@PORTRAIT"] = "Portrait",
    ["face_human@mini_games@generic@p_m_zero"] = "Generic Zero",
    ["FACE_HUMAN@GEN_MALE@BASE"] = "Generic Male",
}

Config.VariationLabels = {
    ["zero_horse_faceonly_face"] = "Zero Horse Face",--EXAMPLE FROM Config.facial_anims ARRAY
    --ADD HERE MORE LABELS IF YOU WANT FROM Config.facial_anims array
}

Config.facial_anims = {
    {"zero_horse_faceonly_face","face_human@test@new_horse"}, -- FIRST PARAM (zero_horse_faceonly_face) FOR LABEL GOES TO Config.VariationLabels array LIKE EXAMPLE
    {"zero_horse_fullbody_merged","face_human@test@new_horse"},
    {"zero_horse_fullbody_face","face_human@test@new_horse"},
    {"zero_horse_fullbody","face_human@test@new_horse"},
    {"analogrom","face_human@test@new_horse"},
    {"analogrom2","face_human@test@new_horse"},
    {"analogrom2_cl","face_human@test@new_horse"},
    {"analogrom2_p4","face_human@test@new_horse"},
    {"analogrom2_test","face_human@test@new_horse"},
    {"analogrom_ears","face_human@test@new_horse"},
    {"rom_v01","face_human@test@new_horse"},
    
    {"aiming_rifle_01","face_human@bill_williamson@variations@aiming"},
    {"aiming_lasso_03","face_human@bill_williamson@variations@aiming"},
    {"aiming_lasso_02","face_human@bill_williamson@variations@aiming"},
    {"aiming_pistol_01","face_human@bill_williamson@variations@aiming"},
    {"aiming_lasso_01","face_human@bill_williamson@variations@aiming"},

    {"brave_01","face_human@gen_female_timid@variations@brave"},
    {"mood_brave_2","face_human@gen_female_timid@variations@brave"},
    {"mood_brave_4","face_human@gen_female_timid@variations@brave"},
    {"mood_brave_1","face_human@gen_female_timid@variations@brave"},
    {"brave_02","face_human@gen_female_timid@variations@brave"},
    {"mood_brave_3","face_human@gen_female_timid@variations@brave"},

    {"bitchy_02","face_human@gen_female_agro@variations@bitchy"},
    {"bitchy_01","face_human@gen_female_agro@variations@bitchy"},

    {"mic_chatter","face_human@test@mp_facial"},

    {"seductive_02","face_human@gen_female@variations@seductive"},
    {"mood_seductive_5","face_human@gen_female@variations@seductive"},
    {"mood_seductive_1","face_human@gen_female@variations@seductive"},
    {"seductive_01","face_human@gen_female@variations@seductive"},
    {"seductive_03","face_human@gen_female@variations@seductive"},
    {"mood_seductive_4","face_human@gen_female@variations@seductive"},
    {"seductive_04","face_human@gen_female@variations@seductive"},
    {"seductive_07","face_human@gen_female@variations@seductive"},
    {"mood_seductive_3","face_human@gen_female@variations@seductive"},
    {"seductive_05","face_human@gen_female@variations@seductive"},
    {"seductive_06","face_human@gen_female@variations@seductive"},
    {"mood_seductive_2","face_human@gen_female@variations@seductive"},

    {"mood_normal_2","face_human@john_marston@variations@normal"},
    {"mood_normal_1","face_human@john_marston@variations@normal"},
    {"normal_03","face_human@john_marston@variations@normal"},
    {"normal_01","face_human@john_marston@variations@normal"},
    {"normal_02","face_human@john_marston@variations@normal"},

    {"happy_02","face_human@gen_male_agro@variations@happy"},
    {"happy_04","face_human@gen_male_agro@variations@happy"},
    {"happy_03","face_human@gen_male_agro@variations@happy"},
    {"happy_01","face_human@gen_male_agro@variations@happy"},
    
    {"blackjack_concentration","face_human@mini_games@blackjack@p_m_zero"},

    {"defuse_01","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_5","face_human@gen_female_agro@variations@defuse"},
    {"defuse_02","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_1","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_6","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_2","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_3","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_7","face_human@gen_female_agro@variations@defuse"},
    {"mood_defuse_4","face_human@gen_female_agro@variations@defuse"},

    {"seductive_01","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_3","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_6","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_2","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_7","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_5","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_4","face_human@abigail_roberts@variations@seductive"},
    {"seductive_02","face_human@abigail_roberts@variations@seductive"},
    {"mood_seductive_1","face_human@abigail_roberts@variations@seductive"},

    {"mood_injured_medium_1","face_human@abigail_roberts@variations@injured"},
    {"mood_injured_mild_1","face_human@abigail_roberts@variations@injured"},

    {"mood_exertion_extreme","face_human@dutch@base"},
    {"die_2","face_human@dutch@base"},
    {"mood_scared","face_human@dutch@base"},
    {"knockout_1","face_human@dutch@base"},
    {"mood_sleeping","face_human@dutch@base"},
    {"mood_aiming_lasso","face_human@dutch@base"},
    {"mood_aiming_pistol","face_human@dutch@base"},
    {"mood_aiming_rifle","face_human@dutch@base"},
    {"mood_angry","face_human@dutch@base"},
    {"mood_blizzard","face_human@dutch@base"},
    {"mood_underfire_heavy","face_human@dutch@base"},
    {"mood_burning","face_human@dutch@base"},
    {"mood_dead_1","face_human@dutch@base"},
    {"pain_1","face_human@dutch@base"},
    {"mood_dead_2","face_human@dutch@base"},
    {"mood_drunk_extreme","face_human@dutch@base"},
    {"pain_2","face_human@dutch@base"},
    {"mood_drunk_medium","face_human@dutch@base"},
    {"mood_drunk_mild","face_human@dutch@base"},
    {"pain_3","face_human@dutch@base"},
    {"mood_underfire","face_human@dutch@base"},
    {"mood_exertion_medium","face_human@dutch@base"},
    {"mood_exertion_mild","face_human@dutch@base"},
    {"pain_4","face_human@dutch@base"},
    {"mood_injured_medium","face_human@dutch@base"},
    {"mood_injured_mild","face_human@dutch@base"},
    {"pain_5","face_human@dutch@base"},
    {"mood_knockout","face_human@dutch@base"},
    {"mood_nervous","face_human@dutch@base"},
    {"pain_6","face_human@dutch@base"},
    {"mood_normal","face_human@dutch@base"},
    {"shoot_gun_01","face_human@dutch@base"},
    {"die_1","face_human@dutch@base"},

    {"die_1","face_human@john_marston@base"},
    {"die_2","face_human@john_marston@base"},
    {"knockout_1","face_human@john_marston@base"},
    {"mood_aiming_lasso","face_human@john_marston@base"},
    {"mood_aiming_pistol","face_human@john_marston@base"},
    {"mood_aiming_rifle","face_human@john_marston@base"},
    {"mood_angry","face_human@john_marston@base"},
    {"mood_burning","face_human@john_marston@base"},
    {"mood_cautious","face_human@john_marston@base"},
    {"mood_dead_1","face_human@john_marston@base"},
    {"mood_dead_2","face_human@john_marston@base"},
    {"mood_drunk_extreme","face_human@john_marston@base"},
    {"mood_drunk_medium","face_human@john_marston@base"},
    {"mood_drunk_mild","face_human@john_marston@base"},
    {"mood_exertion_extreme","face_human@john_marston@base"},
    {"mood_exertion_medium","face_human@john_marston@base"},
    {"mood_exertion_mild","face_human@john_marston@base"},
    {"mood_injured_medium","face_human@john_marston@base"},
    {"mood_injured_mild","face_human@john_marston@base"},
    {"mood_nervous","face_human@john_marston@base"},
    {"mood_normal","face_human@john_marston@base"},
    {"mood_sleeping","face_human@john_marston@base"},
    {"mood_underfire","face_human@john_marston@base"},
    {"mood_underfire_heavy","face_human@john_marston@base"},
    {"pain_1","face_human@john_marston@base"},
    {"pain_2","face_human@john_marston@base"},
    {"pain_3","face_human@john_marston@base"},
    {"pain_4","face_human@john_marston@base"},
    {"pain_5","face_human@john_marston@base"},
    {"pain_6","face_human@john_marston@base"},
    {"pain_7","face_human@john_marston@base"},
    {"shocked_1","face_human@john_marston@base"},
    {"shocked_2","face_human@john_marston@base"},
    {"shocked_3","face_human@john_marston@base"},
    {"shoot_gun_01","face_human@john_marston@base"},

    {"normal_06","face_human@abigail_roberts@variations@normal"},
    {"normal_01","face_human@abigail_roberts@variations@normal"},
    {"normal_02","face_human@abigail_roberts@variations@normal"},
    {"normal_07","face_human@abigail_roberts@variations@normal"},
    {"normal_03","face_human@abigail_roberts@variations@normal"},
    {"normal_04","face_human@abigail_roberts@variations@normal"},
    {"normal_08","face_human@abigail_roberts@variations@normal"},
    {"normal_05","face_human@abigail_roberts@variations@normal"},

    {"sleeping_02","face_human@gen_female_timid@variations@sleeping"},
    {"sleeping_01","face_human@gen_female_timid@variations@sleeping"},
    {"sleeping_03","face_human@gen_female_timid@variations@sleeping"},
    {"mood_sleeping_2","face_human@gen_female_timid@variations@sleeping"},

    {"mood_aiming_pistol_1","face_human@hosea@variations@aiming"},
    {"mood_aiming_rifle_1","face_human@hosea@variations@aiming"},
    {"mood_aiming_pistol_2","face_human@hosea@variations@aiming"},
    {"mood_aiming_lasso_1","face_human@hosea@variations@aiming"},

    {"mood_defuse_2","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_4","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_7","face_human@gen_female_timid@variations@defuse"},
    {"defuse_01","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_1","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_5","face_human@gen_female_timid@variations@defuse"},
    {"defuse_02","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_3","face_human@gen_female_timid@variations@defuse"},
    {"mood_defuse_6","face_human@gen_female_timid@variations@defuse"},

    {"mood_exertion_medium_1","face_human@gen_female@variations@exertion"},
    {"mood_exertion_extreme_1","face_human@gen_female@variations@exertion"},
    {"exertion_medium_03","face_human@gen_female@variations@exertion"},
    {"exertion_medium_04","face_human@gen_female@variations@exertion"},
    {"exertion_medium_02","face_human@gen_female@variations@exertion"},
    {"exertion_medium_01","face_human@gen_female@variations@exertion"},
    {"mood_exertion_mild_1","face_human@gen_female@variations@exertion"},
    {"exertion_extreme_01","face_human@gen_female@variations@exertion"},

    {"drunk_01","face_human@charles_smith@variations@drunk"},
    {"drunk_03","face_human@charles_smith@variations@drunk"},
    {"drunk_02","face_human@charles_smith@variations@drunk"},

    {"pain_3","face_human@bill_williamson@base"},
    {"mood_exertion_extreme","face_human@bill_williamson@base"},
    {"die_1","face_human@bill_williamson@base"},
    {"mood_dead_2","face_human@bill_williamson@base"},
    {"mood_exertion_mild","face_human@bill_williamson@base"},
    {"mood_exertion_medium","face_human@bill_williamson@base"},
    {"shoot_gun_01","face_human@bill_williamson@base"},
    {"mood_dead_1","face_human@bill_williamson@base"},
    {"mood_injured_medium","face_human@bill_williamson@base"},
    {"mood_injured_mild","face_human@bill_williamson@base"},
    {"mood_burning","face_human@bill_williamson@base"},
    {"mood_knockout","face_human@bill_williamson@base"},
    {"mood_angry","face_human@bill_williamson@base"},
    {"mood_nervous","face_human@bill_williamson@base"},
    {"mood_aiming_rifle","face_human@bill_williamson@base"},
    {"mood_drunk_mild","face_human@bill_williamson@base"},
    {"mood_normal","face_human@bill_williamson@base"},
    {"mood_aiming_pistol","face_human@bill_williamson@base"},
    {"mood_drunk_medium","face_human@bill_williamson@base"},
    {"mood_sleeping","face_human@bill_williamson@base"},
    {"mood_aiming_lasso","face_human@bill_williamson@base"},
    {"mood_underfire","face_human@bill_williamson@base"},
    {"pain_1","face_human@bill_williamson@base"},
    {"knockout_1","face_human@bill_williamson@base"},
    {"pain_2","face_human@bill_williamson@base"},
    {"die_2","face_human@bill_williamson@base"},
    {"pain_4","face_human@bill_williamson@base"},

    {"concentration_base_2","face_human@mini_games@poker@gen_male"},
    {"folding_hand","face_human@mini_games@poker@gen_male"},
    {"concentration_base_1","face_human@mini_games@poker@gen_male"},
    {"tell_bad","face_human@mini_games@poker@gen_male"},
    {"concentration_base","face_human@mini_games@poker@gen_male"},
    {"tell_good","face_human@mini_games@poker@gen_male"},
    
    {"facetest_pro_v09_range2","face_human@test@new_head"},
    {"facetest_pro_v09_range1_new","face_human@test@new_head"},
    {"facetest_pro_v09_range1","face_human@test@new_head"},
    {"rom_anm_teen","face_human@test@new_head"},
    {"fish_test","face_human@test@new_head"},
    {"fish_test_face","face_human@test@new_head"},
    {"fishrom","face_human@test@new_head"},
    {"global_eye_only","face_human@test@new_head"},
    {"headmovement_test_01","face_human@test@new_head"},
    {"rom_brows","face_human@test@new_head"},
    {"headnudge","face_human@test@new_head"},
    {"rom_bruising","face_human@test@new_head"},
    {"headnudge_1","face_human@test@new_head"},
    {"headnudge_2","face_human@test@new_head"},
    {"rom_cheeks","face_human@test@new_head"},
    {"headtracking","face_human@test@new_head"},
    {"poses_v04","face_human@test@new_head"},
    {"rom_global_eyes","face_human@test@new_head"},
    {"poses_v05","face_human@test@new_head"},
    {"poses_v1","face_human@test@new_head"},
    {"poses_v2","face_human@test@new_head"},
    {"rom_liproll_dutch","face_human@test@new_head"},
    {"poses_v3","face_human@test@new_head"},
    {"rom_anm","face_human@test@new_head"},
    {"rom_tongue","face_human@test@new_head"},
    {"rom_anm_anger","face_human@test@new_head"},
    {"rom_anm_blush","face_human@test@new_head"},
    {"rom_tweakers","face_human@test@new_head"},
    {"rom_anm_child","face_human@test@new_head"},
    {"rom_v12","face_human@test@new_head"},
    {"rom_wrinklebloodflow","face_human@test@new_head"},
    {"rom_anm_cold","face_human@test@new_head"},
    {"rom_anm_female","face_human@test@new_head"},
    {"zero","face_human@test@new_head"},

    {"mood_exertion_extreme","face_human@micah_bell@base"},
    {"die_1","face_human@micah_bell@base"},
    {"die_2","face_human@micah_bell@base"},
    {"knockout_1","face_human@micah_bell@base"},
    {"mood_aiming_lasso","face_human@micah_bell@base"},
    {"mood_aiming_pistol","face_human@micah_bell@base"},
    {"mood_aiming_rifle","face_human@micah_bell@base"},
    {"mood_angry","face_human@micah_bell@base"},
    {"mood_blizzard","face_human@micah_bell@base"},
    {"mood_dead_1","face_human@micah_bell@base"},
    {"mood_dead_2","face_human@micah_bell@base"},
    {"mood_nervous","face_human@micah_bell@base"},
    {"mood_exertion_medium","face_human@micah_bell@base"},
    {"mood_normal","face_human@micah_bell@base"},
    {"mood_panic","face_human@micah_bell@base"},
    {"mood_drunk_extreme","face_human@micah_bell@base"},
    {"mood_scared","face_human@micah_bell@base"},
    {"mood_injured_mild","face_human@micah_bell@base"},
    {"mood_underfire","face_human@micah_bell@base"},
    {"mood_underfire_heavy","face_human@micah_bell@base"},
    {"mood_exertion_mild","face_human@micah_bell@base"},
    {"mood_underfire_mild","face_human@micah_bell@base"},
    {"pain_1","face_human@micah_bell@base"},
    {"mood_intimidated","face_human@micah_bell@base"},
    {"pain_2","face_human@micah_bell@base"},
    {"mood_injured_medium","face_human@micah_bell@base"},
    {"pain_3","face_human@micah_bell@base"},
    {"mood_drunk_mild","face_human@micah_bell@base"},
    {"pain_4","face_human@micah_bell@base"},
    {"pain_5","face_human@micah_bell@base"},
    {"mood_knockout","face_human@micah_bell@base"},
    {"pain_6","face_human@micah_bell@base"},
    {"shocked_1","face_human@micah_bell@base"},
    {"shocked_2","face_human@micah_bell@base"},
    {"mood_drunk_medium","face_human@micah_bell@base"},
    {"shocked_3","face_human@micah_bell@base"},

    {"cigar_inhale_2_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_l_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_l_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_l_to_exit","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_hold","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_lung_1","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_r_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_r_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_2_to_lung_2","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_r_to_exit","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"cigar_light_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_light_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_inhale_1","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_inhale_2","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_hold","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_lung_1","face_human@gen_male@scenario@smokecig"},
    {"cigar_inhale_1_to_lung_2","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_exhale_to_exit","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_hold_to_light","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_hold","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_lung_1","face_human@gen_male@scenario@smokecig"},
    {"inhale_1_to_lung_2","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_loop_long","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_loop_short","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"cigar_light_to_hold","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_hold","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_lung_1","face_human@gen_male@scenario@smokecig"},
    {"inhale_2_to_lung_2","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_1_to_hold","face_human@gen_male@scenario@smokecig"},
    {"lick_loop_long","face_human@gen_male@scenario@smokecig"},
    {"lick_loop_short","face_human@gen_male@scenario@smokecig"},
    {"lick_to_hold","face_human@gen_male@scenario@smokecig"},
    {"cigar_lung_2_to_hold","face_human@gen_male@scenario@smokecig"},
    {"enter","face_human@gen_male@scenario@smokecig"},
    {"light_loop_long","face_human@gen_male@scenario@smokecig"},
    {"enter_short","face_human@gen_male@scenario@smokecig"},
    {"light_loop_short","face_human@gen_male@scenario@smokecig"},
    {"exhale_l_loop_long","face_human@gen_male@scenario@smokecig"},
    {"exhale_l_loop_short","face_human@gen_male@scenario@smokecig"},
    {"light_to_hold","face_human@gen_male@scenario@smokecig"},
    {"exhale_l_to_exit","face_human@gen_male@scenario@smokecig"},
    {"exhale_loop_long","face_human@gen_male@scenario@smokecig"},
    {"lung_1_loop_long","face_human@gen_male@scenario@smokecig"},
    {"exhale_loop_short","face_human@gen_male@scenario@smokecig"},
    {"exhale_r_loop_long","face_human@gen_male@scenario@smokecig"},
    {"lung_1_loop_short","face_human@gen_male@scenario@smokecig"},
    {"exhale_r_loop_short","face_human@gen_male@scenario@smokecig"},
    {"exhale_r_to_exit","face_human@gen_male@scenario@smokecig"},
    {"lung_1_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"exhale_to_exit","face_human@gen_male@scenario@smokecig"},
    {"hold_loop_long","face_human@gen_male@scenario@smokecig"},
    {"lung_1_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"hold_loop_short","face_human@gen_male@scenario@smokecig"},
    {"hold_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"lung_1_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"hold_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"lung_1_to_hold","face_human@gen_male@scenario@smokecig"},
    {"hold_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"lung_2_loop_long","face_human@gen_male@scenario@smokecig"},
    {"cigar_enter","face_human@gen_male@scenario@smokecig"},
    {"hold_to_inhale_1","face_human@gen_male@scenario@smokecig"},
    {"lung_2_loop_short","face_human@gen_male@scenario@smokecig"},
    {"cigar_enter_short","face_human@gen_male@scenario@smokecig"},
    {"lung_2_to_exhale","face_human@gen_male@scenario@smokecig"},
    {"hold_to_inhale_2","face_human@gen_male@scenario@smokecig"},
    {"lung_2_to_exhale_l","face_human@gen_male@scenario@smokecig"},
    {"hold_to_lick","face_human@gen_male@scenario@smokecig"},
    {"lung_2_to_exhale_r","face_human@gen_male@scenario@smokecig"},
    {"lung_2_to_hold","face_human@gen_male@scenario@smokecig"},
    {"hold_to_light","face_human@gen_male@scenario@smokecig"},

    {"angry_01","face_human@gen_female@variations@angry"},
    {"angry_02","face_human@gen_female@variations@angry"},
    {"angry_03","face_human@gen_female@variations@angry"},
    {"angry_04","face_human@gen_female@variations@angry"},
    {"mood_angry_1","face_human@gen_female@variations@angry"},
    {"angry_06","face_human@gen_female@variations@angry"},
    {"mood_angry_2","face_human@gen_female@variations@angry"},
    {"angry_07","face_human@gen_female@variations@angry"},
    {"mood_angry_3","face_human@gen_female@variations@angry"},
    {"mood_angry_4","face_human@gen_female@variations@angry"},
    {"angry_05","face_human@gen_female@variations@angry"},
    {"mood_angry_5","face_human@gen_female@variations@angry"},
    
    {"mood_exertion_extreme","face_human@gen_male_timid@base"},
    {"blink","face_human@gen_male_timid@base"},
    {"mood_happy","face_human@gen_male_timid@base"},
    {"blinklong","face_human@gen_male_timid@base"},
    {"browangry","face_human@gen_male_timid@base"},
    {"mood_injured_medium","face_human@gen_male_timid@base"},
    {"browsurprise","face_human@gen_male_timid@base"},
    {"bump_1","face_human@gen_male_timid@base"},
    {"mood_injured_mild","face_human@gen_male_timid@base"},
    {"bump_2","face_human@gen_male_timid@base"},
    {"bump_3","face_human@gen_male_timid@base"},
    {"mood_intimidated","face_human@gen_male_timid@base"},
    {"die_1","face_human@gen_male_timid@base"},
    {"die_2","face_human@gen_male_timid@base"},
    {"mood_knockout","face_human@gen_male_timid@base"},
    {"die_3","face_human@gen_male_timid@base"},
    {"die_4","face_human@gen_male_timid@base"},
    {"mood_nervous","face_human@gen_male_timid@base"},
    {"die_5","face_human@gen_male_timid@base"},
    {"exertion_1","face_human@gen_male_timid@base"},
    {"mood_normal","face_human@gen_male_timid@base"},
    {"exertion_2","face_human@gen_male_timid@base"},
    {"fidget_1","face_human@gen_male_timid@base"},
    {"mood_panic","face_human@gen_male_timid@base"},
    {"fidget_2","face_human@gen_male_timid@base"},
    {"fidget_3","face_human@gen_male_timid@base"},
    {"mood_recovery","face_human@gen_male_timid@base"},
    {"fidget_4","face_human@gen_male_timid@base"},
    {"fidget_5","face_human@gen_male_timid@base"},
    {"fidget_6","face_human@gen_male_timid@base"},
    {"mood_sad","face_human@gen_male_timid@base"},
    {"knockout_1","face_human@gen_male_timid@base"},
    {"meleeattackextreme","face_human@gen_male_timid@base"},
    {"mood_scared","face_human@gen_male_timid@base"},
    {"meleeattackmedium","face_human@gen_male_timid@base"},
    {"meleeattackmild","face_human@gen_male_timid@base"},
    {"meleereactextreme_1","face_human@gen_male_timid@base"},
    {"mood_sleeping","face_human@gen_male_timid@base"},
    {"meleereactextreme_2","face_human@gen_male_timid@base"},
    {"meleereactextreme_3","face_human@gen_male_timid@base"},
    {"mood_smug","face_human@gen_male_timid@base"},
    {"meleereactextreme_4","face_human@gen_male_timid@base"},
    {"meleereactextreme_5","face_human@gen_male_timid@base"},
    {"mood_sulk","face_human@gen_male_timid@base"},
    {"meleereactextreme_6","face_human@gen_male_timid@base"},
    {"meleereactmedium_1","face_human@gen_male_timid@base"},
    {"mood_tired","face_human@gen_male_timid@base"},
    {"meleereactmedium_2","face_human@gen_male_timid@base"},
    {"meleereactmedium_3","face_human@gen_male_timid@base"},
    {"mood_underfire","face_human@gen_male_timid@base"},
    {"meleereactmedium_4","face_human@gen_male_timid@base"},
    {"meleereactmedium_5","face_human@gen_male_timid@base"},
    {"mood_underfire_heavy","face_human@gen_male_timid@base"},
    {"meleereactmedium_6","face_human@gen_male_timid@base"},
    {"meleereactmild_1","face_human@gen_male_timid@base"},
    {"mood_underfire_mild","face_human@gen_male_timid@base"},
    {"meleereactmild_2","face_human@gen_male_timid@base"},
    {"meleereactmild_3","face_human@gen_male_timid@base"},
    {"mouth_looted","face_human@gen_male_timid@base"},
    {"meleereactmild_4","face_human@gen_male_timid@base"},
    {"meleereactmild_5","face_human@gen_male_timid@base"},
    {"pain_1","face_human@gen_male_timid@base"},
    {"meleereactmild_6","face_human@gen_male_timid@base"},
    {"mood_aiming_lasso","face_human@gen_male_timid@base"},
    {"pain_2","face_human@gen_male_timid@base"},
    {"mood_aiming_pistol","face_human@gen_male_timid@base"},
    {"mood_aiming_rifle","face_human@gen_male_timid@base"},
    {"pain_3","face_human@gen_male_timid@base"},
    {"mood_angry","face_human@gen_male_timid@base"},
    {"mood_angry_injured","face_human@gen_male_timid@base"},
    {"pain_4","face_human@gen_male_timid@base"},
    {"mood_brave","face_human@gen_male_timid@base"},
    {"mood_burning","face_human@gen_male_timid@base"},
    {"pain_5","face_human@gen_male_timid@base"},
    {"mood_choked","face_human@gen_male_timid@base"},
    {"mood_choked_mild","face_human@gen_male_timid@base"},
    {"pain_6","face_human@gen_male_timid@base"},
    {"mood_cold","face_human@gen_male_timid@base"},
    {"mood_cower","face_human@gen_male_timid@base"},
    {"pain_7","face_human@gen_male_timid@base"},
    {"mood_curious","face_human@gen_male_timid@base"},
    {"mood_dead_1","face_human@gen_male_timid@base"},
    {"shocked_1","face_human@gen_male_timid@base"},
    {"mood_dead_2","face_human@gen_male_timid@base"},
    {"mood_defuse","face_human@gen_male_timid@base"},
    {"shocked_2","face_human@gen_male_timid@base"},
    {"mood_disgust","face_human@gen_male_timid@base"},
    {"mood_drunk_extreme","face_human@gen_male_timid@base"},
    {"shocked_3","face_human@gen_male_timid@base"},
    {"mood_drunk_medium","face_human@gen_male_timid@base"},
    {"mood_drunk_mild","face_human@gen_male_timid@base"},
    {"shoot_gun_01","face_human@gen_male_timid@base"},
    {"mood_exertion_medium","face_human@gen_male_timid@base"},
    {"smoking_exhale_1","face_human@gen_male_timid@base"},
    {"mood_exertion_mild","face_human@gen_male_timid@base"},
    {"smoking_hold_1","face_human@gen_male_timid@base"},
    {"smoking_inhale_1","face_human@gen_male_timid@base"},
    {"mood_exhausted","face_human@gen_male_timid@base"},
    {"take_cover","face_human@gen_male_timid@base"},
    
    {"blink_hard_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_r_exit","face_human@gen_male@scenario@wipeface"},
    {"blink_hard_enter","face_human@gen_male@scenario@wipeface"},
    {"mouth_r_exit_short","face_human@gen_male@scenario@wipeface"},
    {"blink_exit","face_human@gen_male@scenario@wipeface"},
    {"mouth_d_exit","face_human@gen_male@scenario@wipeface"},
    {"brow_d_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_d_exit_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_d_enter","face_human@gen_male@scenario@wipeface"},
    {"brow_d_loop_long","face_human@gen_male@scenario@wipeface"},
    {"brow_u_enter","face_human@gen_male@scenario@wipeface"},
    {"mouth_r_loop_long","face_human@gen_male@scenario@wipeface"},
    {"mouth_d_loop_long","face_human@gen_male@scenario@wipeface"},
    {"brow_d_exit","face_human@gen_male@scenario@wipeface"},
    {"blink_enter","face_human@gen_male@scenario@wipeface"},
    {"mouth_d_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_r_loop_short","face_human@gen_male@scenario@wipeface"},
    {"brow_d_enter","face_human@gen_male@scenario@wipeface"},
    {"brow_u_loop_long","face_human@gen_male@scenario@wipeface"},
    {"brow_u_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_l_enter","face_human@gen_male@scenario@wipeface"},
    {"brow_u_exit","face_human@gen_male@scenario@wipeface"},
    {"blink_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_l_exit","face_human@gen_male@scenario@wipeface"},
    {"blink_loop_long","face_human@gen_male@scenario@wipeface"},
    {"blink_hard_loop_long","face_human@gen_male@scenario@wipeface"},
    {"mouth_l_exit_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_l_loop_long","face_human@gen_male@scenario@wipeface"},
    {"mouth_l_loop_short","face_human@gen_male@scenario@wipeface"},
    {"mouth_r_enter","face_human@gen_male@scenario@wipeface"},
    {"blink_hard_exit","face_human@gen_male@scenario@wipeface"},


    {"openchew_to_closechew","face_human@gen_male@scenario@eating"},
    {"closechew_to_openchew","face_human@gen_male@scenario@eating"},
    {"big_loop_short","face_human@gen_male@scenario@eating"},
    {"med_to_openchew","face_human@gen_male@scenario@eating"},
    {"big_to_closechew","face_human@gen_male@scenario@eating"},
    {"mixchew_loop_long","face_human@gen_male@scenario@eating"},
    {"big_to_openchew","face_human@gen_male@scenario@eating"},
    {"closechew_loop_long","face_human@gen_male@scenario@eating"},
    {"openchew_loop_long","face_human@gen_male@scenario@eating"},
    {"closechew_loop_short","face_human@gen_male@scenario@eating"},
    {"openchew_loop_short","face_human@gen_male@scenario@eating"},
    {"closegulp","face_human@gen_male@scenario@eating"},
    {"enter_big","face_human@gen_male@scenario@eating"},
    {"enter_big_short","face_human@gen_male@scenario@eating"},
    {"enter_med","face_human@gen_male@scenario@eating"},
    {"sml_loop_long","face_human@gen_male@scenario@eating"},
    {"enter_med_short","face_human@gen_male@scenario@eating"},
    {"enter_sml","face_human@gen_male@scenario@eating"},
    {"sml_loop_short","face_human@gen_male@scenario@eating"},
    {"enter_sml_short","face_human@gen_male@scenario@eating"},
    {"med_loop_long","face_human@gen_male@scenario@eating"},
    {"sml_to_closechew","face_human@gen_male@scenario@eating"},
    {"med_loop_short","face_human@gen_male@scenario@eating"},
    {"med_to_closechew","face_human@gen_male@scenario@eating"},
    {"sml_to_openchew","face_human@gen_male@scenario@eating"},
    {"big_loop_long","face_human@gen_male@scenario@eating"},

    {"closegulp","face_human@gen_male@scenario@drinkshot"},
    {"sting_to_strain","face_human@gen_male@scenario@drinkshot"},
    {"enter","face_human@gen_male@scenario@drinkshot"},
    {"enter_short","face_human@gen_male@scenario@drinkshot"},
    {"strain_enter","face_human@gen_male@scenario@drinkshot"},
    {"loop_long","face_human@gen_male@scenario@drinkshot"},
    {"strain_exit","face_human@gen_male@scenario@drinkshot"},
    {"loop_short","face_human@gen_male@scenario@drinkshot"},
    {"sting_closegulp","face_human@gen_male@scenario@drinkshot"},
    {"strain_gasp","face_human@gen_male@scenario@drinkshot"},
    {"sting_enter","face_human@gen_male@scenario@drinkshot"},
    {"sting_exit","face_human@gen_male@scenario@drinkshot"},
    {"strain_loop_long","face_human@gen_male@scenario@drinkshot"},
    {"sting_loop_long","face_human@gen_male@scenario@drinkshot"},
    {"strain_loop_short","face_human@gen_male@scenario@drinkshot"},
    {"sting_loop_short","face_human@gen_male@scenario@drinkshot"},
    {"exit","face_human@gen_male@scenario@drinkshot"},

    {"mood_injured_medium_1","face_human@micah_bell@variations@injured"},
    {"mood_injured_mild_1","face_human@micah_bell@variations@injured"},

    {"meleeattackextreme","face_human@gen_male@melee@base"},
    {"meleeattackmild","face_human@gen_male@melee@base"},
    {"meleereactextreme","face_human@gen_male@melee@base"},
    {"meleeattackmedium","face_human@gen_male@melee@base"},
    {"meleereactmedium","face_human@gen_male@melee@base"},
    {"meleereactmild","face_human@gen_male@melee@base"},

    {"mood_drunk_mild_1","face_human@gen_male_agro@variations@drunk"},
    {"mood_drunk_medium_1","face_human@gen_male_agro@variations@drunk"},

    {"mood_drunk_extreme_1", "face_human@abigail_roberts@variations@drunk"},

    {"mood_normal", "face_human@mrs_adler@base"},

    {"trackshoot","face_human@p_m_zero"},

    {"normal_01","face_human@gen_female_agro@variations@normal"},
    {"normal_03","face_human@gen_female_agro@variations@normal"},
    {"normal_02","face_human@gen_female_agro@variations@normal"},
    {"mood_normal_2","face_human@gen_female_agro@variations@normal"},

    {"angry_01","face_human@gen_female_timid@variations@angry"},
    {"angry_02","face_human@gen_female_timid@variations@angry"},
    {"angry_03","face_human@gen_female_timid@variations@angry"},
    {"mood_angry_2","face_human@gen_female_timid@variations@angry"},
    {"angry_04","face_human@gen_female_timid@variations@angry"},
    {"angry_07","face_human@gen_female_timid@variations@angry"},
    {"angry_05","face_human@gen_female_timid@variations@angry"},
    {"angry_06","face_human@gen_female_timid@variations@angry"},
    {"mood_angry_4","face_human@gen_female_timid@variations@angry"},
    {"mood_angry_5","face_human@gen_female_timid@variations@angry"},
    {"mood_angry_3","face_human@gen_female_timid@variations@angry"},
    {"mood_angry_1","face_human@gen_female_timid@variations@angry"},

    {"mood_exertion_medium_1","face_human@gen_male@variations@exertion"},
    {"mood_exertion_extreme_1","face_human@gen_male@variations@exertion"},
    {"mood_exertion_mild_1","face_human@gen_male@variations@exertion"},
    {"exertion_medium_02","face_human@gen_male@variations@exertion"},
    {"exertion_extreme_01","face_human@gen_male@variations@exertion"},
    {"exertion_medium_01","face_human@gen_male@variations@exertion"},

    {"curious_01","face_human@gen_female_timid@variations@curious"},
    {"curious_02","face_human@gen_female_timid@variations@curious"},
    {"mood_curious_1","face_human@gen_female_timid@variations@curious"},
    {"mood_curious_2","face_human@gen_female_timid@variations@curious"},
    {"mood_curious_3","face_human@gen_female_timid@variations@curious"},
    {"mood_curious_4","face_human@gen_female_timid@variations@curious"},
    {"mood_curious_5","face_human@gen_female_timid@variations@curious"},

    {"aiming_lasso_01","face_human@gen_female@variations@aiming"},
    {"aiming_lasso_01","face_human@gen_male@variations@aiming"},

    {"sleeping_01","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_02","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_03","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_04","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_05","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_06","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_07","face_human@gen_male_timid@variations@sleeping"},
    {"sleeping_08","face_human@gen_male_timid@variations@sleeping"},
    {"mood_sleeping_2","face_human@gen_male_timid@variations@sleeping"},
    
    {"curious_01","face_human@gen_female@variations@curious"},
    {"curious_02","face_human@gen_female@variations@curious"},
    {"mood_curious_1","face_human@gen_female@variations@curious"},
    {"mood_curious_2","face_human@gen_female@variations@curious"},
    {"mood_curious_3","face_human@gen_female@variations@curious"},
    {"mood_curious_4","face_human@gen_female@variations@curious"},
    {"mood_curious_5","face_human@gen_female@variations@curious"},

    {"mood_sleeping_3","face_human@abigail_roberts@variations@sleeping"},
    {"sleeping_01","face_human@abigail_roberts@variations@sleeping"},
    {"sleeping_02","face_human@abigail_roberts@variations@sleeping"},
    {"sleeping_05","face_human@abigail_roberts@variations@sleeping"},
    {"sleeping_03","face_human@abigail_roberts@variations@sleeping"},
    {"mood_sleeping_2","face_human@abigail_roberts@variations@sleeping"},
    {"mood_sleeping_1","face_human@abigail_roberts@variations@sleeping"},
    {"sleeping_04","face_human@abigail_roberts@variations@sleeping"},


    {"blackjack_dealer_bust","face_human@mini_games@blackjack@gen_male"},
    {"blackjack_concentration","face_human@mini_games@blackjack@gen_male"},
    {"blackjack_dealer_win","face_human@mini_games@blackjack@gen_male"},
    {"blackjack_impatient","face_human@mini_games@blackjack@gen_male"},

    {"happy_01","face_human@gen_female@variations@happy"},
    {"happy_02","face_human@gen_female@variations@happy"},
    {"happy_03","face_human@gen_female@variations@happy"},
    {"happy_04","face_human@gen_female@variations@happy"},

    {"mood_normal_1", "face_human@micah_bell@variations@normal"},
    {"mood_normal_2", "face_human@micah_bell@variations@normal"},

    {"happy_01","face_human@gen_male@variations@happy"},
    {"happy_02","face_human@gen_male@variations@happy"},
    {"happy_03","face_human@gen_male@variations@happy"},
    {"happy_04","face_human@gen_male@variations@happy"},


    {"mood_exertion_medium_1","face_human@dutch@variations@exertion"},
    {"mood_exertion_extreme_1","face_human@dutch@variations@exertion"},

    {"closegulp","face_human@gen_male@scenario@drinkhand"},
    {"enter","face_human@gen_male@scenario@drinkhand"},
    {"loop_short","face_human@gen_male@scenario@drinkhand"},
    {"enter_short","face_human@gen_male@scenario@drinkhand"},
    {"opengulp","face_human@gen_male@scenario@drinkhand"},
    {"loop_long","face_human@gen_male@scenario@drinkhand"},
    {"exit","face_human@gen_male@scenario@drinkhand"},

    {"mood_sleeping_2", "FACE_HUMAN@GEN_MALE@VARIATIONS@SLEEPING"},

    {"portrait_normal", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_happy", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_pensive", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_pensive_2", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_relaxed", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_angry", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_angry_2", "FACE_HUMAN@GEN_MALE@PORTRAIT"},
    {"portrait_annoyed", "FACE_HUMAN@GEN_MALE@PORTRAIT"},

    {"call_bet", "face_human@mini_games@generic@p_m_zero"},
    {"winning_hand_big", "face_human@mini_games@generic@p_m_zero"},
    {"losing_hand_big", "face_human@mini_games@generic@p_m_zero"},
    {"losing_hand_normal", "face_human@mini_games@generic@p_m_zero"},
    {"winning_hand_normal", "face_human@mini_games@generic@p_m_zero"},
    {"mood_normal_neutral", "face_human@mini_games@generic@p_m_zero"},
    {"poker_face", "face_human@mini_games@generic@p_m_zero"},

    {"mood_exertion_extreme", "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_intimidated_nervous" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_concentration_extreme" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_intimidated" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_stealth" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_sulk" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"blink" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"blinklong" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_swamp" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"browangry" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"browsurprise" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_swim" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"bump_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_talking_happy" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"bump_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"die_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_talking_normal" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"die_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"die_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_tired" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"die_4" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"die_5" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_underfire" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"exertion_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"exertion_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_underfire_heavy" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"eyefocus" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_underfire_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_water" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_4" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_wind_extreme" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_5" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"fidget_6" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"hitreins_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_wind_medium" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"hitreins_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"hitreins_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_wind_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"hitreins_4" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"kill_cam_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mouth_looted" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"kill_cam_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_angry_defuse" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"kill_cam_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"knockout_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"bump_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_angry_intimidated" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_action" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_aiming_lasso" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_angry_scared" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_aiming_pistol" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_aiming_rifle" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_brave_nervous" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_angry" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_angry_injured" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_brave_panic" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_bitchy" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_blizzard" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_brave_scared" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_blizzard_frozen" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_bracing" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_brave_smug" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_brave" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_burning" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_calmhorse" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_carrylarge" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_angry" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_cautious" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_charging" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_brave" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_choked" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_choked_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_cower" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_choked_rear" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_cocky" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_curious" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_cocky_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_cold" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_defuse" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_combatlow" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_combatmedium" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_concentration" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_disgust" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_confused" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_happy" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_cower" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_curious" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_dead_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_dead_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_panic" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_dead_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_dead_4" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_normal_sad" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_dead_5" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_defuse" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mt_panic_scared" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_disgust" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_drunk_extreme" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"nervous_rider_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_drunk_medium" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"normal_01_sick" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_drunk_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"normal_02_sick" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_exertion_medium" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_exertion_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"normal_03_sick" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_exhausted" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_falllarge" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"normal_04_sick" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_fallsmall" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_foliage" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_happy" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_hot" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_injured_medium" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_injured_mild" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_injuredcritical" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_intimidate" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_4" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_intimidated" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_investigate" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_5" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_knockout" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_lowdeadeye" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_6" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_lowhealth" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_lowstamina" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"pain_7" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_nearfire" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_nervous" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"riding_mood" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_nervous_rider" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shocked_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal_neutral" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal_sick" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shocked_2" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_panic" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_rapids" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_reading" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shocked_3" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_recovery" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_riding" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shoot_gun_01" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_ridingrelax" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_sad" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shoot_gun_02" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_sad_extreme" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_safe_cracking" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shoot_rifle_01" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_scared" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"shoot_rifle_02" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_searchhigh" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_searchlow" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"smoking_exhale_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_seductive" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_shocksmall" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"smoking_hold_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_sleeping" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"smoking_inhale_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"sniff_1" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_slide" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"take_cover" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_smug" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal_zoom" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal_eyes_wide" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"face_dentistry_loop" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"face_dentistry_out" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"face_dentistry_in" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"eyes_wide_exit" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"eyes_wide_enter" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"mood_normal_zoom_01" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"dentistry_loop" , "FACE_HUMAN@GEN_MALE@BASE"},
    {"dentistry_in", "FACE_HUMAN@GEN_MALE@BASE"},
    {"dentistry_out", "FACE_HUMAN@GEN_MALE@BASE"},
}